// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: NoteList
			nil,       // empty
			shift(6),  // [
			nil,       // ]
			shift(8),  // char
			shift(9),  // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			shift(11), // assign
			shift(12), // tempo
			shift(13), // channel
			shift(14), // velocity
			shift(15), // program
			shift(16), // control
			shift(17), // bar
			shift(18), // end
			shift(19), // play
			shift(20), // start
			shift(21), // stop
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // empty
			nil,          // [
			nil,          // ]
			nil,          // char
			nil,          // rest
			nil,          // sharp
			nil,          // flat
			nil,          // accent
			nil,          // ghost
			nil,          // uint
			nil,          // dot
			nil,          // tuplet
			nil,          // letRing
			nil,          // stringLit
			nil,          // assign
			nil,          // tempo
			nil,          // channel
			nil,          // velocity
			nil,          // program
			nil,          // control
			nil,          // bar
			nil,          // end
			nil,          // play
			nil,          // start
			nil,          // stop
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Expr
			nil,       // empty
			nil,       // [
			nil,       // ]
			nil,       // char
			nil,       // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Expr
			nil,       // empty
			nil,       // [
			nil,       // ]
			nil,       // char
			nil,       // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: NoteList
			nil,       // empty
			shift(6),  // [
			nil,       // ]
			shift(8),  // char
			shift(9),  // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: NoteList
			nil,       // empty
			shift(6),  // [
			nil,       // ]
			shift(8),  // char
			shift(9),  // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(27), // [
			reduce(3), // ], reduce: NoteList
			shift(29), // char
			shift(30), // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // $, reduce: PropertyList
			nil,        // empty
			reduce(10), // [, reduce: PropertyList
			nil,        // ]
			reduce(10), // char, reduce: PropertyList
			reduce(10), // rest, reduce: PropertyList
			shift(33),  // sharp
			shift(34),  // flat
			shift(35),  // accent
			shift(36),  // ghost
			shift(37),  // uint
			shift(38),  // dot
			shift(39),  // tuplet
			shift(40),  // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // $, reduce: NoteSymbol
			nil,       // empty
			reduce(8), // [, reduce: NoteSymbol
			nil,       // ]
			reduce(8), // char, reduce: NoteSymbol
			reduce(8), // rest, reduce: NoteSymbol
			reduce(8), // sharp, reduce: NoteSymbol
			reduce(8), // flat, reduce: NoteSymbol
			reduce(8), // accent, reduce: NoteSymbol
			reduce(8), // ghost, reduce: NoteSymbol
			reduce(8), // uint, reduce: NoteSymbol
			reduce(8), // dot, reduce: NoteSymbol
			reduce(8), // tuplet, reduce: NoteSymbol
			reduce(8), // letRing, reduce: NoteSymbol
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(9), // $, reduce: NoteSymbol
			nil,       // empty
			reduce(9), // [, reduce: NoteSymbol
			nil,       // ]
			reduce(9), // char, reduce: NoteSymbol
			reduce(9), // rest, reduce: NoteSymbol
			reduce(9), // sharp, reduce: NoteSymbol
			reduce(9), // flat, reduce: NoteSymbol
			reduce(9), // accent, reduce: NoteSymbol
			reduce(9), // ghost, reduce: NoteSymbol
			reduce(9), // uint, reduce: NoteSymbol
			reduce(9), // dot, reduce: NoteSymbol
			reduce(9), // tuplet, reduce: NoteSymbol
			reduce(9), // letRing, reduce: NoteSymbol
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(21), // $, reduce: ArgumentList
			nil,        // empty
			nil,        // [
			nil,        // ]
			shift(41),  // char
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			shift(42),  // uint
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			shift(44),  // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(25), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(25), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(25), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(25), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(26), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(26), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(26), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(26), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(27), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(27), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(27), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(27), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(28), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(28), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(28), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(28), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(29), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(29), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(29), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(29), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(30), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(30), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(30), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(30), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(31), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(31), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(31), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(31), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(32), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(32), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(32), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(32), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(33), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(33), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(33), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(33), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(34), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(34), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(34), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(34), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(35), // $, reduce: CommandName
			nil,        // empty
			nil,        // [
			nil,        // ]
			reduce(35), // char, reduce: CommandName
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			reduce(35), // uint, reduce: CommandName
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			reduce(35), // stringLit, reduce: CommandName
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // $, reduce: NoteList
			nil,       // empty
			nil,       // [
			nil,       // ]
			nil,       // char
			nil,       // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // $, reduce: NoteList
			nil,       // empty
			nil,       // [
			nil,       // ]
			nil,       // char
			nil,       // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // [
			shift(45), // ]
			nil,       // char
			nil,       // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(27), // [
			reduce(3), // ], reduce: NoteList
			shift(29), // char
			shift(30), // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(27), // [
			reduce(3), // ], reduce: NoteList
			shift(29), // char
			shift(30), // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(27), // [
			reduce(3), // ], reduce: NoteList
			shift(29), // char
			shift(30), // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(10), // [, reduce: PropertyList
			reduce(10), // ], reduce: PropertyList
			reduce(10), // char, reduce: PropertyList
			reduce(10), // rest, reduce: PropertyList
			shift(51),  // sharp
			shift(52),  // flat
			shift(53),  // accent
			shift(54),  // ghost
			shift(55),  // uint
			shift(56),  // dot
			shift(57),  // tuplet
			shift(58),  // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			reduce(8), // [, reduce: NoteSymbol
			reduce(8), // ], reduce: NoteSymbol
			reduce(8), // char, reduce: NoteSymbol
			reduce(8), // rest, reduce: NoteSymbol
			reduce(8), // sharp, reduce: NoteSymbol
			reduce(8), // flat, reduce: NoteSymbol
			reduce(8), // accent, reduce: NoteSymbol
			reduce(8), // ghost, reduce: NoteSymbol
			reduce(8), // uint, reduce: NoteSymbol
			reduce(8), // dot, reduce: NoteSymbol
			reduce(8), // tuplet, reduce: NoteSymbol
			reduce(8), // letRing, reduce: NoteSymbol
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			reduce(9), // [, reduce: NoteSymbol
			reduce(9), // ], reduce: NoteSymbol
			reduce(9), // char, reduce: NoteSymbol
			reduce(9), // rest, reduce: NoteSymbol
			reduce(9), // sharp, reduce: NoteSymbol
			reduce(9), // flat, reduce: NoteSymbol
			reduce(9), // accent, reduce: NoteSymbol
			reduce(9), // ghost, reduce: NoteSymbol
			reduce(9), // uint, reduce: NoteSymbol
			reduce(9), // dot, reduce: NoteSymbol
			reduce(9), // tuplet, reduce: NoteSymbol
			reduce(9), // letRing, reduce: NoteSymbol
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // $, reduce: Note
			nil,       // empty
			reduce(7), // [, reduce: Note
			nil,       // ]
			reduce(7), // char, reduce: Note
			reduce(7), // rest, reduce: Note
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // $, reduce: PropertyList
			nil,        // empty
			reduce(10), // [, reduce: PropertyList
			nil,        // ]
			reduce(10), // char, reduce: PropertyList
			reduce(10), // rest, reduce: PropertyList
			shift(33),  // sharp
			shift(34),  // flat
			shift(35),  // accent
			shift(36),  // ghost
			shift(37),  // uint
			shift(38),  // dot
			shift(39),  // tuplet
			shift(40),  // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(12), // $, reduce: Property
			nil,        // empty
			reduce(12), // [, reduce: Property
			nil,        // ]
			reduce(12), // char, reduce: Property
			reduce(12), // rest, reduce: Property
			reduce(12), // sharp, reduce: Property
			reduce(12), // flat, reduce: Property
			reduce(12), // accent, reduce: Property
			reduce(12), // ghost, reduce: Property
			reduce(12), // uint, reduce: Property
			reduce(12), // dot, reduce: Property
			reduce(12), // tuplet, reduce: Property
			reduce(12), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(13), // $, reduce: Property
			nil,        // empty
			reduce(13), // [, reduce: Property
			nil,        // ]
			reduce(13), // char, reduce: Property
			reduce(13), // rest, reduce: Property
			reduce(13), // sharp, reduce: Property
			reduce(13), // flat, reduce: Property
			reduce(13), // accent, reduce: Property
			reduce(13), // ghost, reduce: Property
			reduce(13), // uint, reduce: Property
			reduce(13), // dot, reduce: Property
			reduce(13), // tuplet, reduce: Property
			reduce(13), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(14), // $, reduce: Property
			nil,        // empty
			reduce(14), // [, reduce: Property
			nil,        // ]
			reduce(14), // char, reduce: Property
			reduce(14), // rest, reduce: Property
			reduce(14), // sharp, reduce: Property
			reduce(14), // flat, reduce: Property
			reduce(14), // accent, reduce: Property
			reduce(14), // ghost, reduce: Property
			reduce(14), // uint, reduce: Property
			reduce(14), // dot, reduce: Property
			reduce(14), // tuplet, reduce: Property
			reduce(14), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(15), // $, reduce: Property
			nil,        // empty
			reduce(15), // [, reduce: Property
			nil,        // ]
			reduce(15), // char, reduce: Property
			reduce(15), // rest, reduce: Property
			reduce(15), // sharp, reduce: Property
			reduce(15), // flat, reduce: Property
			reduce(15), // accent, reduce: Property
			reduce(15), // ghost, reduce: Property
			reduce(15), // uint, reduce: Property
			reduce(15), // dot, reduce: Property
			reduce(15), // tuplet, reduce: Property
			reduce(15), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(16), // $, reduce: Property
			nil,        // empty
			reduce(16), // [, reduce: Property
			nil,        // ]
			reduce(16), // char, reduce: Property
			reduce(16), // rest, reduce: Property
			reduce(16), // sharp, reduce: Property
			reduce(16), // flat, reduce: Property
			reduce(16), // accent, reduce: Property
			reduce(16), // ghost, reduce: Property
			reduce(16), // uint, reduce: Property
			reduce(16), // dot, reduce: Property
			reduce(16), // tuplet, reduce: Property
			reduce(16), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(17), // $, reduce: Property
			nil,        // empty
			reduce(17), // [, reduce: Property
			nil,        // ]
			reduce(17), // char, reduce: Property
			reduce(17), // rest, reduce: Property
			reduce(17), // sharp, reduce: Property
			reduce(17), // flat, reduce: Property
			reduce(17), // accent, reduce: Property
			reduce(17), // ghost, reduce: Property
			reduce(17), // uint, reduce: Property
			reduce(17), // dot, reduce: Property
			reduce(17), // tuplet, reduce: Property
			reduce(17), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(18), // $, reduce: Property
			nil,        // empty
			reduce(18), // [, reduce: Property
			nil,        // ]
			reduce(18), // char, reduce: Property
			reduce(18), // rest, reduce: Property
			reduce(18), // sharp, reduce: Property
			reduce(18), // flat, reduce: Property
			reduce(18), // accent, reduce: Property
			reduce(18), // ghost, reduce: Property
			reduce(18), // uint, reduce: Property
			reduce(18), // dot, reduce: Property
			reduce(18), // tuplet, reduce: Property
			reduce(18), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(19), // $, reduce: Property
			nil,        // empty
			reduce(19), // [, reduce: Property
			nil,        // ]
			reduce(19), // char, reduce: Property
			reduce(19), // rest, reduce: Property
			reduce(19), // sharp, reduce: Property
			reduce(19), // flat, reduce: Property
			reduce(19), // accent, reduce: Property
			reduce(19), // ghost, reduce: Property
			reduce(19), // uint, reduce: Property
			reduce(19), // dot, reduce: Property
			reduce(19), // tuplet, reduce: Property
			reduce(19), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(21), // $, reduce: ArgumentList
			nil,        // empty
			nil,        // [
			nil,        // ]
			shift(41),  // char
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			shift(42),  // uint
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			shift(44),  // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(21), // $, reduce: ArgumentList
			nil,        // empty
			nil,        // [
			nil,        // ]
			shift(41),  // char
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			shift(42),  // uint
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			shift(44),  // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(20), // $, reduce: Command
			nil,        // empty
			nil,        // [
			nil,        // ]
			nil,        // char
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			nil,        // uint
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(21), // $, reduce: ArgumentList
			nil,        // empty
			nil,        // [
			nil,        // ]
			shift(41),  // char
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			shift(42),  // uint
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			shift(44),  // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // $, reduce: PropertyList
			nil,        // empty
			reduce(10), // [, reduce: PropertyList
			nil,        // ]
			reduce(10), // char, reduce: PropertyList
			reduce(10), // rest, reduce: PropertyList
			shift(33),  // sharp
			shift(34),  // flat
			shift(35),  // accent
			shift(36),  // ghost
			shift(37),  // uint
			shift(38),  // dot
			shift(39),  // tuplet
			shift(40),  // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // [
			reduce(4), // ], reduce: NoteList
			nil,       // char
			nil,       // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // [
			reduce(5), // ], reduce: NoteList
			nil,       // char
			nil,       // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // [
			shift(64), // ]
			nil,       // char
			nil,       // rest
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			reduce(7), // [, reduce: Note
			reduce(7), // ], reduce: Note
			reduce(7), // char, reduce: Note
			reduce(7), // rest, reduce: Note
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(10), // [, reduce: PropertyList
			reduce(10), // ], reduce: PropertyList
			reduce(10), // char, reduce: PropertyList
			reduce(10), // rest, reduce: PropertyList
			shift(51),  // sharp
			shift(52),  // flat
			shift(53),  // accent
			shift(54),  // ghost
			shift(55),  // uint
			shift(56),  // dot
			shift(57),  // tuplet
			shift(58),  // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(12), // [, reduce: Property
			reduce(12), // ], reduce: Property
			reduce(12), // char, reduce: Property
			reduce(12), // rest, reduce: Property
			reduce(12), // sharp, reduce: Property
			reduce(12), // flat, reduce: Property
			reduce(12), // accent, reduce: Property
			reduce(12), // ghost, reduce: Property
			reduce(12), // uint, reduce: Property
			reduce(12), // dot, reduce: Property
			reduce(12), // tuplet, reduce: Property
			reduce(12), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(13), // [, reduce: Property
			reduce(13), // ], reduce: Property
			reduce(13), // char, reduce: Property
			reduce(13), // rest, reduce: Property
			reduce(13), // sharp, reduce: Property
			reduce(13), // flat, reduce: Property
			reduce(13), // accent, reduce: Property
			reduce(13), // ghost, reduce: Property
			reduce(13), // uint, reduce: Property
			reduce(13), // dot, reduce: Property
			reduce(13), // tuplet, reduce: Property
			reduce(13), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(14), // [, reduce: Property
			reduce(14), // ], reduce: Property
			reduce(14), // char, reduce: Property
			reduce(14), // rest, reduce: Property
			reduce(14), // sharp, reduce: Property
			reduce(14), // flat, reduce: Property
			reduce(14), // accent, reduce: Property
			reduce(14), // ghost, reduce: Property
			reduce(14), // uint, reduce: Property
			reduce(14), // dot, reduce: Property
			reduce(14), // tuplet, reduce: Property
			reduce(14), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(15), // [, reduce: Property
			reduce(15), // ], reduce: Property
			reduce(15), // char, reduce: Property
			reduce(15), // rest, reduce: Property
			reduce(15), // sharp, reduce: Property
			reduce(15), // flat, reduce: Property
			reduce(15), // accent, reduce: Property
			reduce(15), // ghost, reduce: Property
			reduce(15), // uint, reduce: Property
			reduce(15), // dot, reduce: Property
			reduce(15), // tuplet, reduce: Property
			reduce(15), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(16), // [, reduce: Property
			reduce(16), // ], reduce: Property
			reduce(16), // char, reduce: Property
			reduce(16), // rest, reduce: Property
			reduce(16), // sharp, reduce: Property
			reduce(16), // flat, reduce: Property
			reduce(16), // accent, reduce: Property
			reduce(16), // ghost, reduce: Property
			reduce(16), // uint, reduce: Property
			reduce(16), // dot, reduce: Property
			reduce(16), // tuplet, reduce: Property
			reduce(16), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(17), // [, reduce: Property
			reduce(17), // ], reduce: Property
			reduce(17), // char, reduce: Property
			reduce(17), // rest, reduce: Property
			reduce(17), // sharp, reduce: Property
			reduce(17), // flat, reduce: Property
			reduce(17), // accent, reduce: Property
			reduce(17), // ghost, reduce: Property
			reduce(17), // uint, reduce: Property
			reduce(17), // dot, reduce: Property
			reduce(17), // tuplet, reduce: Property
			reduce(17), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(18), // [, reduce: Property
			reduce(18), // ], reduce: Property
			reduce(18), // char, reduce: Property
			reduce(18), // rest, reduce: Property
			reduce(18), // sharp, reduce: Property
			reduce(18), // flat, reduce: Property
			reduce(18), // accent, reduce: Property
			reduce(18), // ghost, reduce: Property
			reduce(18), // uint, reduce: Property
			reduce(18), // dot, reduce: Property
			reduce(18), // tuplet, reduce: Property
			reduce(18), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(19), // [, reduce: Property
			reduce(19), // ], reduce: Property
			reduce(19), // char, reduce: Property
			reduce(19), // rest, reduce: Property
			reduce(19), // sharp, reduce: Property
			reduce(19), // flat, reduce: Property
			reduce(19), // accent, reduce: Property
			reduce(19), // ghost, reduce: Property
			reduce(19), // uint, reduce: Property
			reduce(19), // dot, reduce: Property
			reduce(19), // tuplet, reduce: Property
			reduce(19), // letRing, reduce: Property
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(11), // $, reduce: PropertyList
			nil,        // empty
			reduce(11), // [, reduce: PropertyList
			nil,        // ]
			reduce(11), // char, reduce: PropertyList
			reduce(11), // rest, reduce: PropertyList
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			nil,        // uint
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(22), // $, reduce: ArgumentList
			nil,        // empty
			nil,        // [
			nil,        // ]
			nil,        // char
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			nil,        // uint
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(24), // $, reduce: ArgumentList
			nil,        // empty
			nil,        // [
			nil,        // ]
			nil,        // char
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			nil,        // uint
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(23), // $, reduce: ArgumentList
			nil,        // empty
			nil,        // [
			nil,        // ]
			nil,        // char
			nil,        // rest
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			nil,        // uint
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // $, reduce: NoteGroup
			nil,       // empty
			reduce(6), // [, reduce: NoteGroup
			nil,       // ]
			reduce(6), // char, reduce: NoteGroup
			reduce(6), // rest, reduce: NoteGroup
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(10), // [, reduce: PropertyList
			reduce(10), // ], reduce: PropertyList
			reduce(10), // char, reduce: PropertyList
			reduce(10), // rest, reduce: PropertyList
			shift(51),  // sharp
			shift(52),  // flat
			shift(53),  // accent
			shift(54),  // ghost
			shift(55),  // uint
			shift(56),  // dot
			shift(57),  // tuplet
			shift(58),  // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(11), // [, reduce: PropertyList
			reduce(11), // ], reduce: PropertyList
			reduce(11), // char, reduce: PropertyList
			reduce(11), // rest, reduce: PropertyList
			nil,        // sharp
			nil,        // flat
			nil,        // accent
			nil,        // ghost
			nil,        // uint
			nil,        // dot
			nil,        // tuplet
			nil,        // letRing
			nil,        // stringLit
			nil,        // assign
			nil,        // tempo
			nil,        // channel
			nil,        // velocity
			nil,        // program
			nil,        // control
			nil,        // bar
			nil,        // end
			nil,        // play
			nil,        // start
			nil,        // stop
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			reduce(6), // [, reduce: NoteGroup
			reduce(6), // ], reduce: NoteGroup
			reduce(6), // char, reduce: NoteGroup
			reduce(6), // rest, reduce: NoteGroup
			nil,       // sharp
			nil,       // flat
			nil,       // accent
			nil,       // ghost
			nil,       // uint
			nil,       // dot
			nil,       // tuplet
			nil,       // letRing
			nil,       // stringLit
			nil,       // assign
			nil,       // tempo
			nil,       // channel
			nil,       // velocity
			nil,       // program
			nil,       // control
			nil,       // bar
			nil,       // end
			nil,       // play
			nil,       // start
			nil,       // stop
		},
	},
}
