// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 10

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Expr
		2,  // NoteList
		4,  // NoteGroup
		5,  // Note
		-1, // PropertyList
		-1, // Property
		3,  // Command
		-1, // ArgumentList
		8,  // CommandName
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Expr
		18, // NoteList
		4,  // NoteGroup
		5,  // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Expr
		19, // NoteList
		4,  // NoteGroup
		5,  // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Expr
		20, // NoteList
		21, // NoteGroup
		22, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		25, // PropertyList
		26, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		36, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Expr
		39, // NoteList
		21, // NoteGroup
		22, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Expr
		40, // NoteList
		21, // NoteGroup
		22, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Expr
		41, // NoteList
		21, // NoteGroup
		22, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		42, // PropertyList
		43, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		51, // PropertyList
		26, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		52, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		53, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		54, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		55, // PropertyList
		26, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		57, // PropertyList
		43, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S49
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S50
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S55
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S56
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		58, // PropertyList
		43, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S57
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S58
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // PropertyList
		-1, // Property
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
}
