// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 10

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Expr
		2,  // NoteAssignment
		3,  // Track
		6,  // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		4,  // Command
		-1, // ArgumentList
		7,  // CommandName
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		18, // NotePropertyList
		19, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		24, // Track
		6,  // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		27, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		30, // NotePropertyList
		19, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		18, // NotePropertyList
		19, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		31, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		32, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // NoteProperty
		-1, // Command
		-1, // ArgumentList
		-1, // CommandName
	},
}
