// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 9

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Expr
		2,  // NoteList
		4,  // NoteGroup
		5,  // Note
		7,  // NoteSymbol
		-1, // PropertyList
		-1, // Property
		3,  // Command
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Expr
		21, // NoteList
		4,  // NoteGroup
		5,  // Note
		7,  // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Expr
		22, // NoteList
		4,  // NoteGroup
		5,  // Note
		7,  // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Expr
		23, // NoteList
		24, // NoteGroup
		25, // Note
		27, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		30, // PropertyList
		31, // Property
		-1, // Command
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Expr
		49, // NoteList
		24, // NoteGroup
		25, // Note
		27, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Expr
		50, // NoteList
		24, // NoteGroup
		25, // Note
		27, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Expr
		51, // NoteList
		24, // NoteGroup
		25, // Note
		27, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		52, // PropertyList
		53, // Property
		-1, // Command
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		62, // PropertyList
		31, // Property
		-1, // Command
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		65, // PropertyList
		31, // Property
		-1, // Command
	},
	gotoRow{ // S49
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S50
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		67, // PropertyList
		53, // Property
		-1, // Command
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S55
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S56
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S57
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S58
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S59
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S60
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S61
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S62
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S63
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S64
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S65
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S66
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		68, // PropertyList
		53, // Property
		-1, // Command
	},
	gotoRow{ // S67
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
	gotoRow{ // S68
		-1, // S'
		-1, // Expr
		-1, // NoteList
		-1, // NoteGroup
		-1, // Note
		-1, // NoteSymbol
		-1, // PropertyList
		-1, // Property
		-1, // Command
	},
}
