// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/mgnsk/gong/internal/parser/token"
)

const (
	NoState    = -1
	NumStates  = 75
	NumSymbols = 84
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '"'
1: '"'
2: '#'
3: '$'
4: '^'
5: ')'
6: '.'
7: '/'
8: '*'
9: '['
10: ']'
11: 'a'
12: 's'
13: 's'
14: 'i'
15: 'g'
16: 'n'
17: 't'
18: 'e'
19: 'm'
20: 'p'
21: 'o'
22: 'c'
23: 'h'
24: 'a'
25: 'n'
26: 'n'
27: 'e'
28: 'l'
29: 'v'
30: 'e'
31: 'l'
32: 'o'
33: 'c'
34: 'i'
35: 't'
36: 'y'
37: 'p'
38: 'r'
39: 'o'
40: 'g'
41: 'r'
42: 'a'
43: 'm'
44: 'c'
45: 'o'
46: 'n'
47: 't'
48: 'r'
49: 'o'
50: 'l'
51: 'b'
52: 'a'
53: 'r'
54: 'e'
55: 'n'
56: 'd'
57: 'p'
58: 'l'
59: 'a'
60: 'y'
61: 's'
62: 't'
63: 'a'
64: 'r'
65: 't'
66: 's'
67: 't'
68: 'o'
69: 'p'
70: '-'
71: '0'
72: '/'
73: '/'
74: '\n'
75: ' '
76: '\t'
77: '\n'
78: '\r'
79: 'a'-'z'
80: 'A'-'Z'
81: '1'-'9'
82: '0'-'9'
83: .
*/
