// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 34: // ['"','"']
			return 2
		case r == 35: // ['#','#']
			return 3
		case r == 36: // ['$','$']
			return 4
		case r == 45: // ['-','-']
			return 5
		case r == 46: // ['.','.']
			return 6
		case r == 47: // ['/','/']
			return 7
		case r == 48: // ['0','0']
			return 8
		case 49 <= r && r <= 57: // ['1','9']
			return 9
		case 65 <= r && r <= 90: // ['A','Z']
			return 5
		case r == 91: // ['[','[']
			return 10
		case r == 93: // [']',']']
			return 11
		case r == 97: // ['a','a']
			return 12
		case r == 98: // ['b','b']
			return 13
		case r == 99: // ['c','c']
			return 14
		case r == 100: // ['d','d']
			return 5
		case r == 101: // ['e','e']
			return 15
		case 102 <= r && r <= 111: // ['f','o']
			return 5
		case r == 112: // ['p','p']
			return 16
		case 113 <= r && r <= 115: // ['q','s']
			return 5
		case r == 116: // ['t','t']
			return 17
		case r == 117: // ['u','u']
			return 5
		case r == 118: // ['v','v']
			return 18
		case 119 <= r && r <= 122: // ['w','z']
			return 5
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 19
		default:
			return 2
		}
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case r == 47: // ['/','/']
			return 20
		case r == 48: // ['0','0']
			return 21
		case 49 <= r && r <= 57: // ['1','9']
			return 22
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 9
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 115: // ['s','s']
			return 23
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 97: // ['a','a']
			return 24
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 104: // ['h','h']
			return 25
		case r == 111: // ['o','o']
			return 26
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 27
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 108: // ['l','l']
			return 28
		case r == 114: // ['r','r']
			return 29
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case r == 101: // ['e','e']
			return 30
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 101: // ['e','e']
			return 31
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 32
		default:
			return 20
		}
	},
	// S21
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 22
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case r == 115: // ['s','s']
			return 33
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 114: // ['r','r']
			return 34
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case r == 97: // ['a','a']
			return 35
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 36
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case r == 100: // ['d','d']
			return 37
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case r == 97: // ['a','a']
			return 38
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case r == 111: // ['o','o']
			return 39
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case r == 109: // ['m','m']
			return 40
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case r == 108: // ['l','l']
			return 41
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case r == 105: // ['i','i']
			return 42
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 43
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case r == 116: // ['t','t']
			return 44
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case r == 121: // ['y','y']
			return 45
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case r == 103: // ['g','g']
			return 46
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case r == 112: // ['p','p']
			return 47
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case r == 111: // ['o','o']
			return 48
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case r == 103: // ['g','g']
			return 49
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 50
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case r == 114: // ['r','r']
			return 51
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case r == 114: // ['r','r']
			return 52
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case r == 111: // ['o','o']
			return 53
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case r == 99: // ['c','c']
			return 54
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 55
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case r == 101: // ['e','e']
			return 56
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case r == 111: // ['o','o']
			return 57
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case r == 97: // ['a','a']
			return 58
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		case r == 105: // ['i','i']
			return 59
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case r == 108: // ['l','l']
			return 60
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		case r == 108: // ['l','l']
			return 61
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case r == 109: // ['m','m']
			return 62
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case r == 116: // ['t','t']
			return 63
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case r == 121: // ['y','y']
			return 64
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
