// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 45: // ['-','-']
			return 2
		case r == 46: // ['.','.']
			return 3
		case r == 47: // ['/','/']
			return 4
		case 49 <= r && r <= 57: // ['1','9']
			return 5
		case r == 61: // ['=','=']
			return 6
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case r == 97: // ['a','a']
			return 8
		case r == 98: // ['b','b']
			return 9
		case 99 <= r && r <= 100: // ['c','d']
			return 8
		case r == 101: // ['e','e']
			return 10
		case 102 <= r && r <= 111: // ['f','o']
			return 8
		case r == 112: // ['p','p']
			return 11
		case 113 <= r && r <= 122: // ['q','z']
			return 8
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case 49 <= r && r <= 57: // ['1','9']
			return 12
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 13
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case r == 97: // ['a','a']
			return 14
		case 98 <= r && r <= 122: // ['b','z']
			return 8
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 109: // ['a','m']
			return 8
		case r == 110: // ['n','n']
			return 15
		case 111 <= r && r <= 122: // ['o','z']
			return 8
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 107: // ['a','k']
			return 8
		case r == 108: // ['l','l']
			return 16
		case 109 <= r && r <= 122: // ['m','z']
			return 8
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 13
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 113: // ['a','q']
			return 8
		case r == 114: // ['r','r']
			return 18
		case 115 <= r && r <= 122: // ['s','z']
			return 8
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 99: // ['a','c']
			return 8
		case r == 100: // ['d','d']
			return 19
		case 101 <= r && r <= 122: // ['e','z']
			return 8
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case r == 97: // ['a','a']
			return 20
		case 98 <= r && r <= 122: // ['b','z']
			return 8
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 120: // ['a','x']
			return 8
		case r == 121: // ['y','y']
			return 21
		case r == 122: // ['z','z']
			return 8
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
}
