// Code generated by tokentypes-gen. DO NOT EDIT.

package tokentype

// Language tokens.
var (
	BracketBegin    = Type{"bracketBegin", 6}
	BracketEnd      = Type{"bracketEnd", 7}
	CmdAssign       = Type{"cmdAssign", 20}
	CmdBar          = Type{"cmdBar", 4}
	CmdChannel      = Type{"cmdChannel", 25}
	CmdControl      = Type{"cmdControl", 27}
	CmdEnd          = Type{"cmdEnd", 5}
	CmdPlay         = Type{"cmdPlay", 21}
	CmdProgram      = Type{"cmdProgram", 26}
	CmdStart        = Type{"cmdStart", 28}
	CmdStop         = Type{"cmdStop", 29}
	CmdTempo        = Type{"cmdTempo", 22}
	CmdTimesig      = Type{"cmdTimesig", 23}
	CmdVelocity     = Type{"cmdVelocity", 24}
	EOF             = Type{"EOF", 1}
	Empty           = Type{"empty", 2}
	INVALID         = Type{"INVALID", 0}
	PropAccent      = Type{"propAccent", 13}
	PropDot         = Type{"propDot", 17}
	PropFlat        = Type{"propFlat", 11}
	PropGhost       = Type{"propGhost", 15}
	PropHeavyAccent = Type{"propHeavyAccent", 14}
	PropLetRing     = Type{"propLetRing", 19}
	PropSharp       = Type{"propSharp", 10}
	PropStaccato    = Type{"propStaccato", 12}
	PropTuplet      = Type{"propTuplet", 18}
	Rest            = Type{"rest", 9}
	Symbol          = Type{"symbol", 8}
	Terminator      = Type{"terminator", 3}
	Uint            = Type{"uint", 16}
)
