// Code generated by tokentypes-gen. DO NOT EDIT.

package tokentype

// Language tokens.
var (
	Accent       = Type{"accent", 12}
	BracketBegin = Type{"bracketBegin", 6}
	BracketEnd   = Type{"bracketEnd", 7}
	CmdAssign    = Type{"cmdAssign", 18}
	CmdBar       = Type{"cmdBar", 4}
	CmdChannel   = Type{"cmdChannel", 23}
	CmdControl   = Type{"cmdControl", 25}
	CmdEnd       = Type{"cmdEnd", 5}
	CmdPlay      = Type{"cmdPlay", 19}
	CmdProgram   = Type{"cmdProgram", 24}
	CmdStart     = Type{"cmdStart", 26}
	CmdStop      = Type{"cmdStop", 27}
	CmdTempo     = Type{"cmdTempo", 20}
	CmdTimesig   = Type{"cmdTimesig", 21}
	CmdVelocity  = Type{"cmdVelocity", 22}
	Dot          = Type{"dot", 15}
	EOF          = Type{"EOF", 1}
	Empty        = Type{"empty", 2}
	Flat         = Type{"flat", 11}
	Ghost        = Type{"ghost", 13}
	INVALID      = Type{"INVALID", 0}
	LetRing      = Type{"letRing", 17}
	Rest         = Type{"rest", 9}
	Sharp        = Type{"sharp", 10}
	Symbol       = Type{"symbol", 8}
	Terminator   = Type{"terminator", 3}
	Tuplet       = Type{"tuplet", 16}
	Uint         = Type{"uint", 14}
)
