// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 7

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Expr
		2,  // NoteAssignment
		3,  // Track
		6,  // NoteList
		-1, // NotePropertyList
		4,  // Command
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		16, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		19, // Track
		6,  // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		28, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		29, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		30, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		16, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Expr
		-1, // NoteAssignment
		-1, // Track
		-1, // NoteList
		-1, // NotePropertyList
		-1, // Command
	},
}
